### PR TITLE
added example script for kinematic weights (using traditional bins)

### PR DESCRIPTION
**Pull request by jackfrost373**

### CODE REVIEW

**Comment by jackfrost373** [comment]
@cpawley @SimonCalo could you review and merge?

**Comment by SimonCalo** [comment]
Wow... That is definitely some code. I really do not think I have the knowledge to fully understand or give some feedback on the code or on the mechanisms used to generate the kinematic weights and use them to reweight the MC. The only thing that I can say is that maybe we should change the Directory indications and make them such that they are interchangeable among the 3 of us. Perhaps we should add the directory that you indicate there to the getDirectory function on the imports module so that we can directly call that function.

**Comment by jackfrost373** [comment]
Thanks for the tip!
However, I'm kind of 'abusing' this folder to be a generic 'examples' folder for useful scripts in the future. The implementation for our case should go into 'Analysis' (one folder up).
You don't have to understand what it's doing, but once we put it in Analysis, you can try running it to see what it does for you?
(Just doing pull requests rather than pushing to master, since I promised Chris)

**Comment by SimonCalo** [comment]
Alright, I see now. Thanks for doing that. Then I guess after @cpawley has taken a look at it, we can merge it right away.

**Comment by jackfrost373** [comment]
Merged since it was a long time ago.

**Pull request merged**
