### PR TITLE
Added trigger cut. Corrected directories

### PR DESCRIPTION
**Pull request by SimonCalo**

### CODE REVIEW

**Comment by jackfrost373** [comment]
@SimonCalo did you also add the Hlt1 and Hlt2 lines?

**Comment by jackfrost373** [comment]
@SimonCalo Any update on adding the Hlt1 trigger as well, and the Hlt2 trigger for run1?

**Comment by jackfrost373** [comment]
@SimonCalo any update on this?

**Comment by SimonCalo** [comment]
As I said on Slack, this pull request should be aborted, because it has been surpassed by the Christmas Update. Should I cole it?

**Pull request closed without merging**
